"""Add Orange Slice blueprint tables.

Revision ID: 0004_orange_slice_upgrade
Revises: 0003_reply_followup_campaigns
Create Date: 2026-06-04
"""

from alembic import op
import sqlalchemy as sa


revision = "0004_orange_slice_upgrade"
down_revision = "0003_reply_followup_campaigns"
branch_labels = None
depends_on = None


def _create_if_missing(existing: set[str], name: str, *columns, **kwargs) -> None:
    if name not in existing:
        op.create_table(name, *columns, **kwargs)


def upgrade() -> None:
    bind = op.get_bind()
    existing = set(sa.inspect(bind).get_table_names())
    _create_if_missing(
        existing,
        "evidence_sources",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("url", sa.Text()),
        sa.Column("publisher", sa.String()),
        sa.Column("source_type", sa.String(), nullable=False, server_default="manual"),
        sa.Column("retrieved_at", sa.DateTime(timezone=True)),
        sa.Column("http_status", sa.Integer()),
        sa.Column("reliability_tier", sa.String(), nullable=False, server_default="operator_supplied"),
        sa.Column("allowed_use", sa.String(), nullable=False, server_default="draft_context"),
        sa.Column("raw_excerpt_redacted", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "lead_facts",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("contact_id", sa.String(), sa.ForeignKey("contacts.id"), nullable=False),
        sa.Column("field_key", sa.String(), nullable=False),
        sa.Column("field_value", sa.Text(), nullable=False),
        sa.Column("source_id", sa.String(), sa.ForeignKey("evidence_sources.id")),
        sa.Column("source_url", sa.Text()),
        sa.Column("source_label", sa.String(), nullable=False, server_default="operator"),
        sa.Column("source_type", sa.String(), nullable=False, server_default="manual"),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="0.5"),
        sa.Column("status", sa.String(), nullable=False, server_default="active"),
        sa.Column("fetched_at", sa.DateTime(timezone=True)),
        sa.Column("expires_at", sa.DateTime(timezone=True)),
        sa.Column("extractor", sa.String(), nullable=False, server_default="operator"),
        sa.Column("raw_snippet_redacted", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "account_facts",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("contact_id", sa.String(), sa.ForeignKey("contacts.id")),
        sa.Column("account_key", sa.String()),
        sa.Column("field_key", sa.String(), nullable=False),
        sa.Column("field_value", sa.Text(), nullable=False),
        sa.Column("source_id", sa.String(), sa.ForeignKey("evidence_sources.id")),
        sa.Column("source_url", sa.Text()),
        sa.Column("source_label", sa.String(), nullable=False, server_default="operator"),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="0.5"),
        sa.Column("status", sa.String(), nullable=False, server_default="active"),
        sa.Column("fetched_at", sa.DateTime(timezone=True)),
        sa.Column("expires_at", sa.DateTime(timezone=True)),
        sa.Column("extractor", sa.String(), nullable=False, server_default="operator"),
        sa.Column("raw_snippet_redacted", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "draft_evidence_checks",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("draft_id", sa.String(), sa.ForeignKey("drafts.id")),
        sa.Column("contact_id", sa.String(), sa.ForeignKey("contacts.id"), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("supported_claims_json", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("missing_evidence_json", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("stale_facts_json", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("neutral_copy_required", sa.Boolean(), nullable=False, server_default="0"),
        sa.Column("neutral_subject", sa.Text()),
        sa.Column("neutral_body", sa.Text()),
        sa.Column("checked_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("policy_version", sa.String(), nullable=False, server_default="evidence_v1"),
    )
    _create_if_missing(
        existing,
        "email_verifications",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("contact_id", sa.String(), sa.ForeignKey("contacts.id")),
        sa.Column("email", sa.String(), nullable=False, unique=True),
        sa.Column("status", sa.String(), nullable=False, server_default="unknown"),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="0"),
        sa.Column("provider", sa.String(), nullable=False, server_default="finimatic_rules"),
        sa.Column("provider_status", sa.String()),
        sa.Column("is_role_based", sa.Boolean(), nullable=False, server_default="0"),
        sa.Column("is_disposable", sa.Boolean(), nullable=False, server_default="0"),
        sa.Column("is_catch_all", sa.Boolean(), nullable=False, server_default="0"),
        sa.Column("mx_present", sa.Boolean(), nullable=False, server_default="0"),
        sa.Column("last_verified_at", sa.DateTime(timezone=True)),
        sa.Column("expires_at", sa.DateTime(timezone=True)),
        sa.Column("raw_response_redacted", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "email_verification_attempts",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("verification_id", sa.String(), sa.ForeignKey("email_verifications.id"), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("response_code", sa.String()),
        sa.Column("latency_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cost_units", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("raw_response_redacted", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "sender_mailboxes",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("email", sa.String(), nullable=False, unique=True),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False, server_default="gmail"),
        sa.Column("transport", sa.String(), nullable=False, server_default="gmail_api"),
        sa.Column("status", sa.String(), nullable=False, server_default="unknown"),
        sa.Column("daily_cap", sa.Integer(), nullable=False, server_default="10"),
        sa.Column("hourly_cap", sa.Integer(), nullable=False, server_default="2"),
        sa.Column("min_delay_s", sa.Integer(), nullable=False, server_default="300"),
        sa.Column("ramp_stage", sa.String(), nullable=False, server_default="low_volume"),
        sa.Column("last_health_check_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "sender_domain_health",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("domain", sa.String(), nullable=False, unique=True),
        sa.Column("spf_status", sa.String(), nullable=False, server_default="unknown"),
        sa.Column("dkim_status", sa.String(), nullable=False, server_default="unknown"),
        sa.Column("dmarc_status", sa.String(), nullable=False, server_default="unknown"),
        sa.Column("alignment_status", sa.String(), nullable=False, server_default="unknown"),
        sa.Column("postmaster_status", sa.String(), nullable=False, server_default="not_connected"),
        sa.Column("spam_rate_bucket", sa.String(), nullable=False, server_default="unknown"),
        sa.Column("reputation_bucket", sa.String(), nullable=False, server_default="unknown"),
        sa.Column("last_checked_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "deliverability_checks",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("sender_email", sa.String()),
        sa.Column("domain", sa.String()),
        sa.Column("check_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False, server_default="unknown"),
        sa.Column("severity", sa.String(), nullable=False, server_default="info"),
        sa.Column("details_redacted", sa.Text()),
        sa.Column("checked_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "inbox_placement_tests",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("sender_email", sa.String(), nullable=False),
        sa.Column("seed_email", sa.String(), nullable=False),
        sa.Column("recipient_domain", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False, server_default="planned"),
        sa.Column("placement", sa.String(), nullable=False, server_default="unknown"),
        sa.Column("provider_msg_id", sa.String()),
        sa.Column("sent_at", sa.DateTime(timezone=True)),
        sa.Column("checked_at", sa.DateTime(timezone=True)),
        sa.Column("details_redacted", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "recipient_domain_caps",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("sender_email", sa.String(), nullable=False),
        sa.Column("recipient_domain", sa.String(), nullable=False),
        sa.Column("daily_cap", sa.Integer(), nullable=False, server_default="10"),
        sa.Column("sent_today", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_sent_at", sa.DateTime(timezone=True)),
        sa.Column("window_date", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False, server_default="active"),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("sender_email", "recipient_domain", "window_date", name="uq_recipient_domain_cap_window"),
    )
    _create_if_missing(
        existing,
        "workbooks",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("status", sa.String(), nullable=False, server_default="draft"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "workbook_rows",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("workbook_id", sa.String(), sa.ForeignKey("workbooks.id"), nullable=False),
        sa.Column("contact_id", sa.String(), sa.ForeignKey("contacts.id")),
        sa.Column("row_key", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False, server_default="pending"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "workbook_columns",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("workbook_id", sa.String(), sa.ForeignKey("workbooks.id"), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("step_type", sa.String(), nullable=False),
        sa.Column("config_json", sa.Text()),
        sa.Column("position", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "workflow_runs",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("workbook_id", sa.String(), sa.ForeignKey("workbooks.id"), nullable=False),
        sa.Column("status", sa.String(), nullable=False, server_default="queued"),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        sa.Column("created_by", sa.String(), nullable=False, server_default="operator"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "workflow_steps",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("workflow_run_id", sa.String(), sa.ForeignKey("workflow_runs.id"), nullable=False),
        sa.Column("workbook_column_id", sa.String(), sa.ForeignKey("workbook_columns.id")),
        sa.Column("step_type", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("status", sa.String(), nullable=False, server_default="queued"),
        sa.Column("config_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "workflow_step_attempts",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("workflow_step_id", sa.String(), sa.ForeignKey("workflow_steps.id"), nullable=False),
        sa.Column("workbook_row_id", sa.String(), sa.ForeignKey("workbook_rows.id")),
        sa.Column("status", sa.String(), nullable=False, server_default="queued"),
        sa.Column("attempt_num", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("input_hash", sa.String(), nullable=False),
        sa.Column("step_config_hash", sa.String(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cost_units", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("error_code", sa.String()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "cell_outputs",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("workbook_id", sa.String(), sa.ForeignKey("workbooks.id"), nullable=False),
        sa.Column("workbook_row_id", sa.String(), sa.ForeignKey("workbook_rows.id"), nullable=False),
        sa.Column("workbook_column_id", sa.String(), sa.ForeignKey("workbook_columns.id"), nullable=False),
        sa.Column("workflow_step_id", sa.String(), sa.ForeignKey("workflow_steps.id")),
        sa.Column("input_hash", sa.String(), nullable=False),
        sa.Column("step_config_hash", sa.String(), nullable=False),
        sa.Column("output_json", sa.Text(), nullable=False),
        sa.Column("evidence_refs", sa.Text()),
        sa.Column("cost_units", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("status", sa.String(), nullable=False, server_default="completed"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("workbook_row_id", "workbook_column_id", "input_hash", "step_config_hash", name="uq_cell_output_hash"),
    )
    _create_if_missing(
        existing,
        "integration_connections",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("account_label", sa.String(), nullable=False, server_default="default"),
        sa.Column("status", sa.String(), nullable=False, server_default="not_connected"),
        sa.Column("auth_mode", sa.String(), nullable=False, server_default="manual"),
        sa.Column("scopes_redacted", sa.Text()),
        sa.Column("last_checked_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("provider", "account_label", name="uq_integration_connection_provider_account"),
    )
    _create_if_missing(
        existing,
        "integration_mappings",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("connection_id", sa.String(), sa.ForeignKey("integration_connections.id"), nullable=False),
        sa.Column("local_field", sa.String(), nullable=False),
        sa.Column("external_field", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False, server_default="push"),
        sa.Column("transform_json", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "sync_journals",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("connection_id", sa.String(), sa.ForeignKey("integration_connections.id")),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("external_id", sa.String()),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False, unique=True),
        sa.Column("diff_json_redacted", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "external_write_previews",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False, server_default="upsert"),
        sa.Column("diff_json_redacted", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False, unique=True),
        sa.Column("status", sa.String(), nullable=False, server_default="pending_confirmation"),
        sa.Column("expires_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "external_write_attempts",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("preview_id", sa.String(), sa.ForeignKey("external_write_previews.id")),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("response_code", sa.String()),
        sa.Column("external_id", sa.String()),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("error_code", sa.String()),
        sa.Column("details_redacted", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    _create_if_missing(
        existing,
        "pending_agent_actions",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("session_id", sa.String(), sa.ForeignKey("agent_sessions.id")),
        sa.Column("action_type", sa.String(), nullable=False),
        sa.Column("capability", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String()),
        sa.Column("params_hash", sa.String(), nullable=False),
        sa.Column("source_label", sa.String(), nullable=False, server_default="System"),
        sa.Column("confirmation_prompt", sa.Text(), nullable=False),
        sa.Column("action_snapshot_redacted", sa.Text()),
        sa.Column("policy_snapshot_redacted", sa.Text()),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False, server_default="0"),
        sa.Column("consumed_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    for table in [
        "pending_agent_actions",
        "external_write_attempts",
        "external_write_previews",
        "sync_journals",
        "integration_mappings",
        "integration_connections",
        "cell_outputs",
        "workflow_step_attempts",
        "workflow_steps",
        "workflow_runs",
        "workbook_columns",
        "workbook_rows",
        "workbooks",
        "recipient_domain_caps",
        "inbox_placement_tests",
        "deliverability_checks",
        "sender_domain_health",
        "sender_mailboxes",
        "email_verification_attempts",
        "email_verifications",
        "draft_evidence_checks",
        "account_facts",
        "lead_facts",
        "evidence_sources",
    ]:
        op.drop_table(table)
